name: Build the i686-cc image
on:
  push:
    # branches:
    #   - "main"
    #   - "master"
    paths:
    - 'build/i686-cc/**'
  release:
    types: [published]
jobs:
  push-to-ghcr:
    name: Build and Push to the github container repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ':latest'
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: build/i686-cc
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/i686-cc:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          context: build/i686-cc
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/i686-cc:${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max